version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:14.5-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=databasename